## => Site Settings
##############################
# url     : https://mairlab.kookmin.ac.kr
url     : https://mairlab-KM.github.io
title   : MAIR Lab @ Kookmin University
description: > # this means to ignore newlines until "Language & timezone"
  Multimodal Auditory & Intelligent Robotics Lab @ Kookmin University

# Text --> bundle exec jekyll serve
# text_skin: "forest"
# highlight_theme: "tomorrow-night-blue"

## => Language and Timezone
##############################
timezone: Asia/Seoul


## => Author and Social
##############################
author:
  type      : organization
  name      : MAIR Lab @ Kookmin University
  avatar    : /assets/images/logo.png
  email     : inkyu.an@kookmin.ac.kr
  # youtube   : ku-plrg
  # github    : ku-plrg


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: mairlab-KM/mairlab-KM.github.io
repository_tree: main


## => Paths
##############################
paths:
  home    : /posts/


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-4.0


## => Markdown Enhancements
##############################
# Mathjax
# (See https://kitian616.github.io/jekyll-TeXt-theme/post/2017/07/07/mathjax.html)
mathjax: true
mathjax_autoNumber: true

# Mermaid
# (See https://kitian616.github.io/jekyll-TeXt-theme/post/2017/06/06/mermaid.html)
mermaid: true

# Chart
# (See https://kitian616.github.io/jekyll-TeXt-theme/post/2017/05/05/chart.html)
chart: true


## => Paginate
##############################
paginate: 8
paginate_path: /posts/page:num


## => Search
##############################
# search:
#   provider: default # "default" (default), false, "google", "custom"

#   ## Google Custom Search Engine
#   google:
#     custom_search_engine_id: # Google Custom Search Engine ID


## => Analytics
##############################
# analytics:
#   provider: google

#   ## Google Analytics
#   google:
#     tracking_id : G-RPGXB995RD


## => Build
##############################
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      aside:
        toc: true
      show_author_profile: true
      show_edit_on_github: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-redirect-from
